apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-acme-statefulset
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-acme-statefulset # has to match .spec.template.metadata.labels
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-acme-statefulset # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
